# Site
repository: Slohrsh/slohrsh.github.io
favicon: images/favicon.ico

# Personal info
name: Sebastian Lohr
title: Junior Software Developer
email: business@sebastian-lohr.de

darkmode: true

# Social links
github_username:  slohrsh
facebook_username: sebastian.lohr.52
instagram_username: slohrsh.photography
linkedin_username: sebastian-lohr-7bb9a3b9
xing_username: Sebastian_Lohr5

# About Section
about_title: Über mich
about_profile_image: images/profile.jpg
quote: >
  Immer neue Ziele setzen, ständig über sich hinauswachsen. Sich selbst übertrumpfen und stets die Komfortzone verlassen. 
  Neue Dinge lernen und mit Freude in neuen Projekten umsetzen.
about_content: | 
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

# Projects Section
projects_title: Big 5 of Life

# Experience Section
experience_title: Erfahrung

# Education Section
education_title: Ausbildung

# More Section
more_title: Nett to know
more_content: | 
  Neben meiner Tätigkeit als Software Entwickler brenne ich für:
   - Fotografie
   - Gitarre für mich selbst spielen
   - Themen über persönliche Weiterentwicklung
   - Fitness Sport

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
