# Site
repository: Slohrsh/slohrsh.github.io
favicon: images/favicon.ico

# Personal info
name: Sebastian Lohr
title: Junior Software Developer
email: business@sebastian-lohr.de

darkmode: true

# Social links
github_username:  slohrsh
facebook_username: sebastian.lohr.52
instagram_username: slohrsh.photography
linkedin_username: sebastian-lohr-7bb9a3b9
xing_username: Sebastian_Lohr5

# About Section
about_title: Über mich
about_profile_image: images/profile.jpg
about_content: | 
  <i>Immer neue Ziele setzen, ständig über sich hinauswachsen. Sich selbst übertrumpfen und stets die Komfortzone verlassen. 
  Neue Dinge lernen und mit Freude in neuen Projekten umsetzen.</i>

  Meine Neugier ist das, was mich antreibt. Ich interessiere mich sehr für Software Architektur und bilde mich unglaublich gern selber weiter.
  Seit 2018 gehe ich jährlich auf die <a href="https://www.code-days.de/">Code Days.</a> Ich suche ständig nach neuen Herausforderungen 
  und möglichkeiten mein Wissen in kleinen Projekten einzusetzen oder durch größere Projekte neues wissen zu erlangen.

  Mein aktuelles Projekt ist ein größeres, das mir die Chance bietet mich in Angular einzuarbeiten. Da es ein kommerzielles Ziel hat,
  freue ich mich schon darauf Angular im vollen umfang von der Entwicklung bis zum Deployment kennenzulernen. Was mich aber fast noch mehr fruet,
  ist dass wir im Backend AWS einsetzen und ich so mich umfangreich dort einarbeiten kann. Es macht einfach unheimlich Spaß zu sehen, wie alle
  Services dort ineinandergreifen.
  
# Projects Section
projects_title: Big Five of Life

# Experience Section
experience_title: Erfahrung

# Education Section
education_title: Ausbildung

# More Section
more_title: Nett to know
more_content: | 
  Neben meiner Tätigkeit als Software Entwickler brenne ich für:
   - Fotografie
   - Gitarre spielen
   - Themen über persönliche Weiterentwicklung
   - Fitness Sport

   Podcasts die ich sehr empfehlen kann:
   - <a href="https://www.innoq.com/de/podcast/">INNOQ Podcast</a> 
   ~ Der INOOQ Podcast ist unglaublich gut um einen Überblick über die Technologien und Architekturpatterns zu bekommen, 
   die gerade angesagt sind. Man merkt sofort mit wie viel Herz und Leidenschaft die Mitarbeiter 
   über ihre Passion reden. Ich empfehle sehr mal reinzuhören. Mir hat es schon viel für meine Projekte gebracht.
   - <a href="https://www.heise.de/developer/podcast/">SoftwareArchitekTOUR-Podcas(ch)t.</a> ~ Der Podcast hat meine Leidenschaft für 
   Software-Architektur geweckt. Noch während meiner Studenzeit habe ich angefangen diesen Podcast zu verschlingen. Dabei wurde mir klar,
   dass ich auch Architekt werden möchte. Es ist unheimlich interessant und bereichernd diesem Podcast zuzuhören.
   - <a href="https://www.steffenkirchner.de/kostenlose-inhalte/alle-folgen-podcast-motivation-erfolg.php">Lebensstark Podcast</a> ~
   Steffen Kirchner ist wirkleich ein herausragender Personalcoach. Er hat es von der ersten Folge an geschafft mein Leben zu verändern.
   Er ist nicht zuletzt ein großer Grund wieso es diese Website hier gibt und hat mein Handeln nachhaltig zum besseren verändert.
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
