# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Sebastian Lohr
title: Junior Software Developer
email: business@sebastian-lohr.de
# website: www.github.com/slohrsh

# Social links
# twitter_username: 
github_username:  slohrsh
# dribbble_username: jekyll
facebook_username: sebastian.lohr.52
# flickr_username: jekyll
instagram_username: slohrsh.photography
linkedin_username: sebastian-lohr-7bb9a3b9
# pinterest_username: jekyll
# youtube_username: sebastian-lohr-7bb9a3b9
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Immer neue Ziele setzen, ständig über sich hinauswachsen. Sich selbst übertrumpfen und stets die Komfortzone verlassen. 
  Neue Dinge lernen und mit Freude in neuen Projekten umsetzen.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Neben meiner Tätigkeit als Software Entwickler brenne ich für:
   - Fotografie
   - Gitarre für mich selbst spielen
   - Themen über persönliche Weiterentwicklung
   - Fitness Sport

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
