repository: Slohrsh/slohrsh.github.io
favicon: images/favicon.ico

name: Sebastian Lohr
title: Junior Software Developer
email: business@sebastian-lohr.de
phone: +49 151 72135311

gtag: "UA-156249213-1"

github_username:  slohrsh
instagram_username: slohrsh.photography
linkedin_username: sebastian-lohr-7bb9a3b9
xing_username: Sebastian_Lohr5


about_title: Über mich
about_profile_image: images/profile.jpg
about_content: | 
  <i>"Immer neue Ziele setzen, ständig über sich hinauswachsen. Sich selbst übertrumpfen und stets die Komfortzone verlassen. 
  Neue Dinge lernen und mit Freude in neuen Projekten umsetzen"</i>

  Meine Neugier ist was mich antreibt. Mein Interesse gilt insbesondere der Software
  Architektur. In diesem und dazugehörigen Bereichen bilde ich mich selbst mit großer Freude
  stetig weiter. Seit 2018 besuche ich jährlich die <a href="https://www.code-days.de/">Code Days.</a> Auf der Suche nach neuen
  Herausforderungen und Möglichkeiten meine Fähigkeiten anzuwenden und neues Wissen
  anzueignen ist mir kein Projekt zu klein oder zu groß.

  Derzeit befasse ich mich intensiv mit Angular um ein größeres Projekt mit kommerziellem
  Ziel umzusetzen. Angular wird mich dabei von der Entwicklung bis zum Deployment
  begleiten. Im Backend wird AWS eingesetzt, in das ich mich parallel zu Angular umfassend
  einarbeite. Das ineinandergreifen von allen möglichen Services fasziniert mich hierbei
  besonders.
  
projects_title: Big Five for Life

experience_title: Erfahrungen

education_title: Ausbildung

more_title: Hobbys und Interessen
more_content: | 
  Neben meiner Tätigkeit als Software Entwickler brenne ich für:
   - Fotografie
   - Gitarre spielen
   - Themen über persönliche Weiterentwicklung
   - Fitness Sport

   Podcasts die ich sehr empfehlen kann:
   - <a href="https://www.innoq.com/de/podcast/">INNOQ Podcast</a> 
   ~ Der INOOQ Podcast ist unglaublich gut um einen Überblick über die Technologien und Architekturpatterns zu bekommen, 
   die gerade angesagt sind. Man merkt sofort mit wie viel Herz und Leidenschaft die Mitarbeiter 
   über ihre Passion reden. Ich empfehle sehr mal reinzuhören. Mir hat es schon viel für meine Projekte gebracht.
   - <a href="https://www.heise.de/developer/podcast/">SoftwareArchitekTOUR-Podcas(ch)t.</a> ~ Der Podcast hat meine Leidenschaft für 
   Software-Architektur geweckt. Noch während meiner Studienzeit habe ich angefangen diesen Podcast zu verschlingen. Dabei wurde mir klar,
   dass ich auch Architekt werden möchte. Es ist unheimlich interessant und bereichernd diesem Podcast zuzuhören.
   - <a href="https://www.steffenkirchner.de/kostenlose-inhalte/alle-folgen-podcast-motivation-erfolg.php">Lebensstark Podcast</a> ~
   Steffen Kirchner ist wirklich ein herausragender Personalcoach. Er hat es von der ersten Folge an geschafft mein Leben zu verändern.
   Er ist nicht zuletzt ein Grund wieso es diese Website hier gibt und hat mein Handeln nachhaltig zum Besseren verändert.
footer_show_references: false

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
